# Generated by Django 5.0.1 on 2024-02-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thietbi",
            name="type",
            field=models.IntegerField(choices=[(0, "Type1"), (1, "Type2")], default=0),
        ),
    ]
