# Generated by Django 5.0.1 on 2024-02-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_delete_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                ("number", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.device"
                    ),
                ),
            ],
        ),
    ]
