# Generated by Django 5.0.1 on 2024-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_data_data_data_x_data_y_data_z"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="y",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="z",
            field=models.FloatField(),
        ),
    ]
