# Generated by Django 5.0.1 on 2024-02-20 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_alter_data_x_alter_data_y_alter_data_z"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
