# Generated by Django 5.0.1 on 2024-04-04 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_data_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                ("number", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z", models.FloatField()),
            ],
        ),
    ]
